services:
  app:
    image: yt-dlp-docker
    build:
      context: .
      no_cache: true
      args:
        CHANNEL: nightly
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ${PWD}:/yt-dlp-downloads
